### ISSUE TITLE
Documento de Léxicos

### ISSUE THREAD

**Issue by AmandaNbr** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#10]
## Descrição da Issue
Elaboração do documento de Léxicos.

## Tasks:
- [x] Definir os léxicos até o momento atual do projeto
- [x] Documentar os Léxicos

## Critérios de Aceitação:
- [x] Documento que contenha os Léxicos divididos nas 3 categorias, e contento as noções e impactos corretamente
