### ISSUE TITLE
Alteração da nomenclatura no documento de politica de branch

### ISSUE THREAD

**Issue by Thais-ra** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#109]
## Descrição da Issue
Alteração simples das nomenclaturas utilizadas nas branches. 

## Tasks:
- [x] Documentation para docs
- [x] Hotfix para fix
- [x] Feature para feat
