### ISSUE TITLE
Correção do documento de NFR Framework

### ISSUE THREAD

**Issue by AnaCarolinaRodriguesLeite** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#136]
## Descrição da Issue:
Implementar a correção do documento, incluindo os pontos de feedback da professora.

## Tasks:
- [x] Corrigir os diagramas.
- [x] Colocar as segunda versão no documento.

## Critérios de Aceitação:
- [x] Documento estar correto
- [ ] Corrigido por revisor
