### ISSUE TITLE
Criar politica de branches

### ISSUE THREAD

**Issue by Thais-ra** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#14]
## Descrição da Issue
Criação de politica contendo o padrão a ser seguido durante o desenvolvimento de todo o projeto.

## Tasks:
- [x] Criar politica
- [ ] Adicionar as politicas de contribuição

## Critérios de Aceitação:
- [x] Estar de acordo com o padrão de documentos
- [ ] Ser revisado por outro membro
