### ISSUE TITLE
Documentar a reunião do dia 25/07

### ISSUE THREAD

**Issue by AnaCarolinaRodriguesLeite** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#149]
## Descrição da Issue
Realizar a documentação da ata de reunião.

## Tasks:
- [ ] Criar a ata de reunião
- [ ] Estar documentada no git

## Critérios de Aceitação:
- [ ] Documento estar correto
- [ ] Corrigido por revisor
