### ISSUE TITLE
Padrões de projeto emergentes

### ISSUE THREAD

**Issue by matheuscvp** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#151]
## Descrição da Issue
<p>Documentar os padrões de projeto emergentes utilizados no projeto e apresentá-los em sala de aula por meio de slides, confeccionados por todos da equipe.</p>

## Tasks:
- [ ] Decidir os padrões emergentes que serão utilizados
- [ ] Documentar os padrões emergentes na wiki
- [ ] Apresentar os padrões em sala de aula

## Critérios de Aceitação:
- [ ] Os padrões de projeto devem ser os utilizados no projeto
- [ ] O documento deve explicar corretamente os padrões de projetos
- [ ] Slide ter sido confeccionado por todos do grupo

## Assignees
@matheuscvp 
@matheusyanmonteiro 

## Milestone
Sprint 5
