### ISSUE TITLE
Diagrama de causa e efeito

### ISSUE THREAD

**Issue by Thais-ra** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#17]
## Descrição da Issue
Artefato sobre o diagrama de ishikawa contendo o diagrama feito pelo grupo e a elaboração do mesmo usando a ferramenta draw.io

## Tasks:
- [x] Brainstorming para a versão inicial
- [x] Diagramar pelo draw.io
- [x] Documentar o processo

## Critérios de Aceitação:
- [x] Seguir padrão do template
- [x] Ser revisado por outro membro
- [ ] Estar na wiki
