### ISSUE TITLE
Mapa mental

### ISSUE THREAD

**Issue by AnaCarolinaRodriguesLeite** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#19]
## Descrição da Issue
Criação do mapa mental que foi desenvolvido inicialmente durante uma reunião no quadro de sala.

## Tasks:
- [x] Criar mapa mental.
- [x] Adicionar os documento em pdf.

## Critérios de Aceitação:
- [x] Estar de acordo com o padrão de documentos.
- [x] Ser revisado por outro membro.
