### ISSUE TITLE
Elicitação por introspecção

### ISSUE THREAD

**Issue by Thais-ra** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#22]
## Descrição da Issue
Elicitação de requisitos utilizando o metodo de introspecção.

## Tasks:
- [x] Fazer instrospecção
- [x] Documentar
- [ ] Colocar na wiki

## Critérios de Aceitação:
- [x] Seguir as politicas de contribuiçao
- [x] Seguir o template para artefatos
- [x] Ser revisado por um membro que não participou da construção do artefato
