### ISSUE TITLE
Ata de reunião 16-06

### ISSUE THREAD

**Issue by AnaCarolinaRodriguesLeite** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#27]
## Descrição da Issue
Criação da ata de reunião 16-06

## Tasks:
- [x] Criar a ata de reunião.

## Critérios de Aceitação:
- [x] Estar de acordo com o padrão de documentos.
- [x] Ser revisado pro outro membro.
