### ISSUE TITLE
Documento de BPMN

### ISSUE THREAD

**Issue by AnaCarolinaRodriguesLeite** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#33]
## Descrição da Issue
Criação do documento de BPMN.

## Tasks:
- [x] Criar os diagramas de cada situação.
- [x] Adicionar os documento em pdf.

## Critérios de Aceitação:
- [x] Estar de acordo com o padrão de documentos.
- [x] Ser revisado por outro membro.
