### ISSUE TITLE
Priorização de requisitos

### ISSUE THREAD

**Issue by Thais-ra** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#38]
## Descrição da Issue
Priorizar os requisitos elicitados pro diferentes técnicas.

## Tasks:
- [x] Organizar os requisitos elicitados, eliminando duplicações
- [x] Priorizar os requisitos com toda a equipe
- [x] Documentar

## Critérios de Aceitação:
- [x] O documento precisa ser revisado por outro membro da equipe
- [x] O documento precisa estar disponível na wiki
