### ISSUE TITLE
Protótipo de Alta fidelidade

### ISSUE THREAD

**Issue by matheuscvp** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#44]
## Descrição da Issue
Realizar a elaboração do protótipo de alta fidelidade de acordo com o guia de estilo do projeto.

## Tasks:
- [ ] Criar o Protótipo de Alta Fidelidade
- [ ] Documentar o protótipo criado

## Critérios de Aceitação:
- [ ] Protótipo estar seguindo o guia de estilo
- [ ] Estar corretamente documentado

## Assignees
@matheuscvp 
@irwinschmitt
