### ISSUE TITLE
Adicionar Diagrama de Estados

### ISSUE THREAD

**Issue by matheuscvp** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#68]
## Descrição da Issue
Realizar a confecção do artefato Diagrama de Estados, seguindo os padrões UML, e documentá-lo corretamente.

## Tasks:
- [ ] Criar o Diagrama
- [ ] Documentar o Diagrama

## Critérios de Aceitação:
- [ ] O Diagrama estar feito
- [ ] O Diagrama estar de acordo com a UML
- [ ] Estar corretamente Documentado

## Assignees
@matheuscvp @mateusmaiamaia 

## Milestone
Sprint 1
