### ISSUE TITLE
Adicionar Diagrama de Componentes

### ISSUE THREAD

**Issue by matheuscvp** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#69]
## Descrição da Issue
Realizar a confecção do Diagrama de Componentes do projeto e documentá-lo corretamente.

## Tasks:
- [ ] Criar o Diagrama
- [ ] Documentar o Diagrama

## Critérios de Aceitação:
- [ ] Diagrama estar correto
- [ ] Diagrama estar de acordo com as normas
- [ ] Diagrama estar corretamente documentado

## Assignees
@matheuscvp @lbvx 

## Milestone
Sprint 1
