### ISSUE TITLE
Diagrama estático - Implantação

### ISSUE THREAD

**Issue by AnaCarolinaRodriguesLeite** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#70]
## Descrição da Issue
Realizar a confecção do Diagrama de Implantação do projeto e documentá-lo corretamente.

## Tasks:
- [x] Criar o Diagrama
- [x] Documentar o Diagrama

## Critérios de Aceitação:
 - [ ] Diagrama estar correto
 - [ ] Diagrama estar de acordo com as normas
 - [ ] Diagrama estar corretamente documentado
