### ISSUE TITLE
Diagrama de sequencia 

### ISSUE THREAD

**Issue by matheusyanmonteiro** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#72]
## Descrição da Issue
É necessario fazer os diagramas de sequencia da aplicação. 

## Tasks:
- [ ] Criar os diagramas
- [ ] Documentar os diagramas

## Critérios de Aceitação:
- [ ] Diagrama estar correto
- [ ] Diagrama estar corretamente documentado
