### ISSUE TITLE
Artefato Rich Picture

### ISSUE THREAD

**Issue by lbvx** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#8]
## Descrição da Issue
Elaboração do documento de Rich Picture.

## Tasks:
- [x] Elaborar Rich Picture final
- [x] Documento do Rich Picture

## Critérios de Aceitação:
- [x] Rich Pictures individuais no documento
- [x] Rich Picture final no documento
