### ISSUE TITLE
Ata de reunião - 06/07

### ISSUE THREAD

**Issue by AnaCarolinaRodriguesLeite** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#89]
## Descrição da Issue
Realizar a documentação da ata de reunião.

## Tasks:
- [x] Criar a ata de reunião
- [x] Estar documentada no git

## Critérios de Aceitação:
- [x] Documento estar correto
- [ ] Corrigido por revisor
