### ISSUE TITLE
Criar o NFR Framework

### ISSUE THREAD

**Issue by AnaCarolinaRodriguesLeite** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#90]
## Descrição da Issue
Documento de NFR Framework como documento extra.

## Tasks:
- [x] Criar o NFR Framework
- [x] Estar documentada no git

## Critérios de Aceitação:
- [ ] Documento estar correto
- [ ] Corrigido por revisor
