### ISSUE TITLE
Atualizar e incremetar o BPMN

### ISSUE THREAD

**Issue by AnaCarolinaRodriguesLeite** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#91]
## Descrição da Issue
Realizar a atualização do BPMN e adicionar os novos diagramas.

## Tasks:
- [x] Atualizar o BPMN
- [x] Estar documentada no git

## Critérios de Aceitação:
- [ ] Documento estar correto
- [ ] Corrigido por revisor
